; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32_ota

[env:esp32_usb]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    h2zero/NimBLE-Arduino
    https://github.com/mathieucarbou/ESPAsyncWebServer.git
    https://github.com/mathieucarbou/AsyncTCP.git
    https://github.com/ayushsharma82/WebSerial

[env:esp32_ota]
extends = env:esp32_usb
upload_protocol = espota
upload_port = 10.0.0.13 ; Inserisci qui l'IP del tuo ESP32
upload_flags =
    --auth=admin